version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    volumes:
      - .n8n:/home/node/.n8n
      - ./generatexcookie.js:/home/node/generatexcookie.js
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=true
      - WEBHOOK_URL=https://lomfabrizio.duckdns.org:8443
      - N8N_HOST=lomfabrizio.duckdns.org
      - N8N_PORT=5678
    restart: unless-stopped
    networks:
      - n8n_network
      
  image-editor:
    image: image-editor-api
    container_name: image-editor
    volumes:
      - ./image-editor/app.py:/app/app.py
      - ./image-editor/fonts:/app/fonts/
    build:
      context: ./image-editor
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - n8n_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
      - "444:443"
      - "8443:8443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=lomfabrizio.duckdns.org
      - NGINX_PORT=443
    restart: unless-stopped
    depends_on:
      - n8n
    networks:
      - n8n_network
      




#  go-whisper:
#    image: onerahmet/openai-whisper-asr-webservice:latest
#    container_name: go-whisper
#    environment:
#      - ASR_MODEL=tiny  # large, small, tiny
#    restart: unless-stopped
#    networks:
#      - n8n_network

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n_data: